Feature: To validate the account creation of fb application

Scenario: To create new account
Given TO LAUNCH THE BROWSER AND MAXIMIZE THE WINDOW
When TO LAUNCH THE URL
And TO CLICK THE CRETE NEW ACCOUNT BUTTON
And TO PASS THE FIRSTNAME IN THE FIRSTNAME TEXTBOX
And TO PASS THE SECONDNAME IN THE SECONDNAME TEXTBOX
And TO PASS THE EMAIL OR MOBILLENUMBER IN THE EMAILTEXTBOX
And TO  PASS THE PASSWORD IN THE PASSWORD TEXTBOX
Then CLOSE THE BROWSER
